### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by pavanshinde47** [deepscan/atom-deepscan#1]
deepscan suddenly stopped working for me on Atom. I have atom=deepscan 1.4.2 and Atom 1.28.2

**Comment by cimfalab** [comment]
Thank you for the issue!
I was using Atom 1.28.1 so just updated to the latest 1.28.2 with DeepScan 1.4.2.
But I could see DeepScan package is working.

Would you check the following?
* Restart Atom and check the problem persists
* Check the settings: Enable and Server
  * Enable should be checked
  * Server should be empty (default) or https://deepscan.io
  * Can you access https://deepscan.io/demo in your browser?

**Comment by cimfalab** [comment]
Dear,
I hope you resolved the issue after restarting Atom.
If you have the problem again, please leave a comment. :eyes:

Thank you again for using this package!
